(function(){
const hunterRequirements={D:{pushups:30,pullups:8,plank:90,wallSit:120,mobility:45},C:{pushups:40,pullups:10,plank:120,wallSit:180,mobility:60},B:{pushups:50,pullups:15,plank:150,wallSit:240,mobility:75},A:{pushups:75,pullups:20,plank:180,wallSit:240,mobility:90},S:{pushups:100,pullups:25,plank:240,wallSit:300,mobility:120}};
const hunterLabels={weight:'Peso',pushups:'Flexoes maximas',pullups:'Barras maximas',plank:'Prancha maxima',wallSit:'Wall Sit',mobility:'Mobilidade'};
const bossMetrics=[{key:'pushups',label:'Flexoes',unit:' reps'},{key:'pullups',label:'Barras',unit:' reps'},{key:'plank',label:'Prancha',unit:'s'},{key:'wallSit',label:'Wall Sit',unit:'s'},{key:'mobility',label:'Mobilidade',unit:'s'}];
const bossTimeCapSeconds=15*60;
const rankKeys=['E','D','C','B','A','S'];
const mobilityProgression={E:'30s',D:'45s',C:'60s',B:'75s',A:'90s',S:'120s'};
const exerciseProgressions={Flexao:{E:'4x8-10 normal',D:'4x12 normal',C:'4x15 normal',B:'4x12 declinada',A:'4x8 archer',S:'4x8 pseudo planche'},'Remada com mochila':{E:'4x12 com 5kg',D:'4x12 com 8kg',C:'4x12 com 12kg',B:'4x10 com 16kg',A:'4x10 com 20kg',S:'4x8 com 25kg'},'Remada mochila':{E:'4x12 com 5kg',D:'4x12 com 8kg',C:'4x12 com 12kg',B:'4x10 com 16kg',A:'4x10 com 20kg',S:'4x8 com 25kg'},'Flexao diamante':{E:'3x6',D:'3x8',C:'3x10',B:'4x10',A:'4x12',S:'4x15'},Prancha:{E:'3x30s',D:'3x45s',C:'3x60s',B:'3x75s',A:'3x90s',S:'3x120s'},Superman:{E:'3x12',D:'3x15',C:'3x20',B:'4x20',A:'4x25',S:'4x30'},Agachamento:{E:'4x12 livre',D:'4x15 livre',C:'4x20 livre',B:'4x12 com mochila 8kg',A:'4x12 com mochila 15kg',S:'4x10 pistol assistido'},Afundo:{E:'3x8 por perna',D:'3x12 por perna',C:'4x12 por perna',B:'4x10 com mochila 8kg',A:'4x10 com mochila 15kg',S:'4x8 bulgaro com mochila 15kg'},'Ponte de gluteo':{E:'3x15 livre',D:'3x20 livre',C:'4x20 livre',B:'4x15 unilateral',A:'4x20 unilateral',S:'4x12 unilateral com mochila'},'Panturrilha unilateral':{E:'3x15',D:'3x20',C:'4x20',B:'4x25',A:'4x30',S:'4x20 com mochila 10kg'},'Saltos verticais':{E:'5x3',D:'5x5',C:'6x5',B:'6x6',A:'8x5',S:'10x5'},'Prancha lateral':{E:'3x20s',D:'3x30s',C:'3x45s',B:'3x60s',A:'3x75s',S:'3x90s'},'Pike push-up':{E:'4x6',D:'4x8',C:'4x10',B:'4x12',A:'4x8 pes elevados',S:'4x10 pes elevados'},'Flexao aberta':{E:'3x10',D:'3x15',C:'4x15',B:'4x20',A:'4x15 declinada',S:'4x12 explosiva'},'Y-T-W deitado':{E:'3x8',D:'3x12',C:'3x15',B:'4x15',A:'4x20',S:'4x20 com pausa de 2s'},'Dead Bug':{E:'3x10',D:'3x15',C:'4x15',B:'4x20',A:'4x20 com pausa',S:'4x20 com controle lento'},'Hollow Hold':{E:'3x20s',D:'3x30s',C:'3x45s',B:'3x60s',A:'3x75s',S:'3x90s'}};
const exerciseRestRules={upper:{seconds:45,names:['Flexao','Remada com mochila','Remada mochila','Flexao diamante','Pike push-up','Flexao aberta','Y-T-W deitado','Wall Angels','Superman']},legs:{seconds:60,names:['Agachamento','Afundo','Ponte de gluteo','Panturrilha unilateral']},core:{seconds:30,names:['Prancha','Prancha lateral','Dead Bug','Hollow Hold','Bird Dog','Prancha leve','Respiracao leve']},explosion:{seconds:75,names:['Saltos verticais']},mobility:{seconds:20,names:['Aquecimento','Mobilidade tornozelo e quadril','Mobilidade de quadril','Mobilidade de tornozelo','Alongamento posterior']}};
const supersets=[{first:'Flexao',second:'Remada com mochila',repeatRest:90}];
let activeRestTimer=null,activeBossTimer=null;
const baseDefaultState=defaultState;
defaultState=function(){const base=baseDefaultState();return{...base,hunterExams:[],hunterRankXp:0,hunterAttributes:null,rusty:{active:false,startedAt:'',maxRankXp:0,currentRankXp:0,lastTrainingDate:'',clearedForTrainingDate:''},bossFight:{active:false,startedAt:0,endsAt:0,progress:{},status:''}}};
state=normalizeState(state);
document.addEventListener('DOMContentLoaded',()=>{setupHunterExam();setupBossFight();renderAll()});
function normalizeState(current){const fresh=defaultState();return{...fresh,...current,rusty:{...fresh.rusty,...(current.rusty||{})},bossFight:{...fresh.bossFight,...(current.bossFight||{})},hunterExams:current.hunterExams||[],hunterRankXp:Number(current.hunterRankXp||0),hunterAttributes:current.hunterAttributes||null}}
function rankKey(name){const text=String(name).toUpperCase();return rankKeys.find(key=>text.includes('RANK '+key))||'E'}
function effectiveXp(){return Math.max(0,isRusty()?Number(state.rusty.currentRankXp||0):Number(state.hunterRankXp||0))}
function nextHunterRank(){const current=rankKey(getRank(effectiveXp()).name);return rankKeys[rankKeys.indexOf(current)+1]||''}
renderAll=function(){syncRustyState();renderDashboard();renderMissions();renderAttributes();renderAchievements();renderWorkouts();renderHunterExam();renderBossFight();renderRanks();renderHistory()};
renderDashboard=function(){const xp=effectiveXp(),level=Math.floor(state.totalXp/200)+1,levelXp=state.totalXp%200,rank=getRank(xp),maxRank=getRank(Number(state.hunterRankXp||0)),next=ranks.find(r=>r.minXp>xp);currentRank.textContent=rank.name;currentLevel.textContent=level;xpText.textContent=levelXp+' / 200 XP de missoes';totalXpText.textContent=isRusty()?'Rank atual: '+xp+' XP | Rank maximo: '+maxRank.name+' (-100 XP)':'Rank Hunter: '+xp+' XP';xpBar.style.width=(levelXp/200*100)+'%';rankHint.textContent=isRusty()?'Status Enferrujado ativo. Venca o Boss Fight para restaurar seu rank.':next?'Proxima promocao no Exame Hunter: '+next.name+'.':'Rank maximo alcancado no Exame Hunter.';const banner=document.getElementById('rustyBanner');if(banner)banner.innerHTML=isRusty()?`<article class='rusty-banner'><div><p class='eyebrow'>Status negativo</p><h2>ENFERRUJADO</h2><p>30 dias sem treino registrado. Voce perdeu 100 XP e seu Rank Atual caiu 1 nivel, mas seu Rank Maximo foi preservado.</p></div><button class='primary-button' type='button' data-open-boss>Ir para Boss Fight</button></article>`:''};
attributeValues=function(){return state.hunterAttributes||attributes.reduce((map,name)=>{map[name]={level:1,progress:0};return map},{})};
renderRanks=function(){const cur=getRank(effectiveXp());ranksGrid.innerHTML=ranks.map(r=>`<article class='rank-card ${r.name===cur.name?'current':''}'><p class='eyebrow'>${r.minXp} XP</p><h3>${r.name}</h3><ul>${r.requirements.map(i=>'<li>'+i+'</li>').join('')}</ul></article>`).join('')};
maxOf=function(s,key){return Math.max(0,...(s.records||[]).map(r=>Number(r[key]||0)),...(s.hunterExams||[]).map(r=>Number(r[key]||0)))};
weightGain=function(s){const entries=[...(s.records||[]),...(s.hunterExams||[])].filter(r=>r.weight).sort((a,b)=>new Date(b.date)-new Date(a.date));if(entries.length<2)return 0;return entries[0].weight-entries[entries.length-1].weight};
function exerciseName(item){if(item.startsWith('Aquecimento:'))return 'Aquecimento';if(item.startsWith('Respiracao'))return 'Respiracao leve';const parts=item.split(' '),tokenIndex=parts.findIndex(part=>part.includes('x')&&!Number.isNaN(Number(part.split('x')[0])));return tokenIndex>0?parts.slice(0,tokenIndex).join(' '):item.trim()}
function exerciseVolume(item){const parts=item.split(' '),token=parts.find(part=>part.includes('x')&&!Number.isNaN(Number(part.split('x')[0])));if(!token)return{series:'Livre',reps:'Tempo por rank'};return{series:token.split('x')[0],reps:parts.slice(parts.indexOf(token)).join(' ').split('x').slice(1).join('x')}}
function exerciseRest(name,previous){const rest={...Object.values(exerciseRestRules).find(group=>group.names.includes(name))||exerciseRestRules.core};const pair=supersets.find(item=>previous===item.first&&name===item.second);if(pair)rest.seconds=pair.repeatRest;return rest}
function exerciseProgression(name){return exerciseProgressions[name]||mobilityProgression}
renderWorkouts=function(){const current=rankKey(getRank(effectiveXp()).name);workoutsGrid.innerHTML=workouts.map(w=>{const plans=w.items.map((item,index)=>{const name=exerciseName(item),volume=exerciseVolume(item),previous=index?w.items[index-1]:'';return{name,series:volume.series,reps:volume.reps,next:w.items[index+1]?exerciseName(w.items[index+1]):'Fim do treino',rest:exerciseRest(name,exerciseName(previous||'')),progression:exerciseProgression(name)}});return `<article class='workout-card'><div class='workout-heading'><div><p class='eyebrow'>${w.day}</p><h3>${w.name}</h3></div><span class='pill'>Rank atual: ${current}</span></div>${renderSuperset(plans)}<div class='exercise-table-wrap'><table class='exercise-table'><thead><tr><th>Exercicio</th><th>Series/Reps</th><th>Descanso</th>${rankKeys.map(rank=>`<th class='${rank===current?'current-rank':''}'>Rank ${rank}</th>`).join('')}<th>Wiki</th></tr></thead><tbody>${plans.map(plan=>renderExerciseRow(plan,current)).join('')}</tbody></table></div></article>`}).join('');document.querySelectorAll('[data-exercise]').forEach(button=>button.addEventListener('click',()=>openExerciseWiki(button.dataset.exercise)));document.querySelectorAll('[data-rest]').forEach(button=>button.addEventListener('click',()=>startRestTimer(Number(button.dataset.rest),button)))};
function renderExerciseRow(plan,current){return `<tr><td><strong>${escapeHtml(plan.name)}</strong><span>Proximo: ${escapeHtml(plan.next)}</span></td><td>${escapeHtml(plan.series+'x'+plan.reps)}</td><td><strong>${plan.rest.seconds}s</strong><button class='rest-button compact' type='button' data-rest='${plan.rest.seconds}'>Iniciar</button></td>${rankKeys.map(rank=>`<td class='${rank===current?'current-rank':''}'>${escapeHtml(plan.progression[rank])}</td>`).join('')}<td><button class='wiki-button compact' type='button' data-exercise='${escapeHtml(plan.name)}'>Ver wiki</button></td></tr>`}
function renderSuperset(plans){const pair=supersets.find(item=>plans.some((plan,index)=>plan.name===item.first&&plans[index+1]&&plans[index+1].name===item.second));if(!pair)return '';const first=plans.find(plan=>plan.name===pair.first),second=plans.find(plan=>plan.name===pair.second);return `<div class='superset-flow'><span>${escapeHtml(first.name)}</span><strong>&darr; ${first.rest.seconds} s</strong><span>${escapeHtml(second.name)}</span><strong>&darr; ${second.rest.seconds} s</strong><span>Repetir</span></div>`}
function startRestTimer(seconds,button){if(activeRestTimer){clearInterval(activeRestTimer.id);activeRestTimer.button.disabled=false;activeRestTimer.button.textContent='Iniciar'}let remaining=seconds;button.disabled=true;button.textContent=formatTimer(remaining);activeRestTimer={button,id:setInterval(()=>{remaining-=1;button.textContent=remaining>0?formatTimer(remaining):'Pronto';if(remaining<=0){clearInterval(activeRestTimer.id);button.disabled=false;activeRestTimer=null}},1000)}}
function formatTimer(seconds){return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
function setupHunterExam(){const start=document.getElementById('startHunterExam'),form=document.getElementById('hunterExamForm'),intro=document.getElementById('hunterIntro'),cancel=document.getElementById('cancelHunterExam');if(!start||!form)return;start.addEventListener('click',()=>{intro.hidden=true;form.hidden=false;hunterResult.innerHTML='';hunterTargetRank.textContent=nextHunterRank()?'Alvo: Rank '+nextHunterRank():'Rank maximo';hunterWeight.focus()});cancel.addEventListener('click',()=>{form.reset();form.hidden=true;intro.hidden=false});form.addEventListener('submit',event=>{event.preventDefault();finishHunterExam()})}
function finishHunterExam(){const exam={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString().slice(0,10),weight:Number(hunterWeight.value),pushups:Number(hunterPushups.value),pullups:Number(hunterPullups.value),plank:Number(hunterPlank.value),wallSit:Number(hunterWallSit.value),mobility:Number(hunterMobility.value),notes:hunterNotes.value.trim(),previousRank:rankKey(getRank(effectiveXp()).name)};const target=nextHunterRank(),previous=state.hunterExams[0],missing=target?missingRequirements(exam,target):[];exam.targetRank=target||exam.previousRank;exam.previousExam=previous?{weight:previous.weight,pushups:previous.pushups,pullups:previous.pullups,plank:previous.plank,wallSit:previous.wallSit,mobility:previous.mobility}:null;if(target&&missing.length===0){exam.status='promoted';exam.rankAfter=target;state.hunterRankXp=ranks.find(r=>rankKey(r.name)===target).minXp;state.hunterAttributes=computeHunterAttributes(exam,target)}else{exam.status=target?'failed':'max';exam.rankAfter=exam.previousRank}exam.missing=missing;state.hunterExams.unshift(exam);saveState();hunterExamForm.reset();hunterExamForm.hidden=true;hunterIntro.hidden=false;renderAll();renderHunterResult(exam)}
function missingRequirements(exam,rank){const req=hunterRequirements[rank];return Object.keys(req).filter(key=>exam[key]<req[key]).map(key=>({key,label:hunterLabels[key],current:exam[key],required:req[key]}))}
function computeHunterAttributes(exam,rank){const bonus=rankKeys.indexOf(rank)*55;return{Forca:scoreToLevel(exam.pushups+exam.pullups*5+bonus),Hipertrofia:scoreToLevel(exam.weight+exam.pushups+bonus),Core:scoreToLevel(exam.plank+exam.wallSit*.35+bonus),Mobilidade:scoreToLevel(exam.mobility+bonus),Postura:scoreToLevel(exam.mobility+exam.plank*.35+bonus),Explosao:scoreToLevel(exam.wallSit*.25+exam.pushups+bonus),Joelhos:scoreToLevel(exam.wallSit*.5+exam.mobility+bonus)}}
function renderHunterExam(){const list=document.getElementById('hunterExamList');if(!list)return;const last=state.hunterExams[0],next=nextHunterRank();hunterExamCount.textContent=state.hunterExams.length+' exames';hunterTargetRank.textContent=next?'Alvo: Rank '+next:'Rank maximo';list.innerHTML=state.hunterExams.length?state.hunterExams.map(renderHunterExamCard).join(''):`<article class='history-card'><p>Nenhum Exame Hunter registrado ainda.</p></article>`;if(!hunterResult.innerHTML&&last)hunterResult.innerHTML=`<article class='hunter-result ${last.status==='promoted'?'promoted':'failed'}'><p class='eyebrow'>Ultimo resultado</p><h2>${hunterStatus(last)}</h2><p>${hunterSummary(last)}</p></article>`}
function renderHunterResult(exam){hunterResult.innerHTML=`<article class='hunter-result ${exam.status==='promoted'?'promoted':'failed'}'><p class='eyebrow'>Resultado do Exame Hunter</p><h2>${hunterStatus(exam)}</h2><p>${hunterSummary(exam)}</p>${hunterComparison(exam)}${hunterMissing(exam)}${hunterUnlocks(exam)}</article>`}
function renderHunterExamCard(exam){return `<article class='history-card hunter-history-card'><div class='section-title'><h3>${formatDate(exam.date)}</h3><span class='pill'>${hunterStatus(exam)}</span></div><div class='history-meta'><span>${exam.weight} kg</span><span>Flexoes ${exam.pushups}</span><span>Barras ${exam.pullups}</span><span>Prancha ${exam.plank}s</span><span>Wall Sit ${exam.wallSit}s</span><span>Mobilidade ${exam.mobility}s</span></div>${exam.notes?'<p>'+escapeHtml(exam.notes)+'</p>':''}${hunterMissing(exam)}</article>`}
function hunterStatus(exam){return exam.status==='promoted'?'PROMOVIDO':exam.status==='max'?'RANK MAXIMO':'REPROVADO'}
function hunterSummary(exam){if(exam.status==='promoted')return 'Rank, atributos, cargas e exercicios desbloqueados foram atualizados para Rank '+exam.rankAfter+'.';if(exam.status==='max')return 'Voce ja esta no limite atual do Projeto Atlas.';return 'Rank mantido em '+exam.rankAfter+'. Complete os requisitos pendentes para promover no proximo exame.'}
function hunterComparison(exam){if(!exam.previousExam)return `<p class='hunter-note'>Primeiro exame registrado. Ele sera a base de comparacao daqui em diante.</p>`;return `<div class='hunter-compare'>${['weight','pushups','pullups','plank','wallSit','mobility'].map(key=>{const diff=exam[key]-Number(exam.previousExam[key]||0);return `<span>${hunterLabels[key]}: ${diff>=0?'+':''}${diff.toFixed(key==='weight'?1:0)}</span>`}).join('')}</div>`}
function hunterMissing(exam){if(!exam.missing||!exam.missing.length)return '';return `<div class='hunter-missing'><h3>Requisitos faltando</h3><ul>${exam.missing.map(item=>`<li>${item.label}: ${item.current} / ${item.required}</li>`).join('')}</ul></div>`}
function hunterUnlocks(exam){return exam.status==='promoted'?`<div class='hunter-unlocks'><h3>Atualizado</h3><div class='history-meta'><span>Rank ${exam.rankAfter}</span><span>Atributos liberados</span><span>Cargas Rank ${exam.rankAfter}</span><span>Exercicios desbloqueados</span></div></div>`:''}
function isRusty(){return !!(state.rusty&&state.rusty.active)}
function syncRustyState(){if(isRusty())return;const last=lastTrainingRecord();if(!last||!last.date||state.rusty.clearedForTrainingDate===last.date)return;const days=Math.floor((startOfToday()-new Date(last.date+'T00:00:00'))/(1000*60*60*24));if(days<30)return;const maxXp=Number(state.hunterRankXp||0);state.rusty={...state.rusty,active:true,startedAt:new Date().toISOString().slice(0,10),maxRankXp:maxXp,currentRankXp:downgradeRankXp(maxXp),lastTrainingDate:last.date};state.totalXp=Math.max(0,state.totalXp-100);state.bossFight={active:false,startedAt:0,endsAt:0,progress:{},status:'unlocked'};saveState()}
function lastTrainingRecord(){return (state.records||[]).filter(r=>r.date&&completedTrainingDays(r)>0).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]}
function startOfToday(){const today=new Date();today.setHours(0,0,0,0);return today}
function downgradeRankXp(xp){const current=rankKey(getRank(xp).name),index=rankKeys.indexOf(current),target=rankKeys[Math.max(0,index-1)];return ranks.find(r=>rankKey(r.name)===target).minXp}
function setupBossFight(){document.addEventListener('click',event=>{if(event.target.matches('[data-open-boss]')){switchTab('boss');setTimeout(()=>bossFightPanel.scrollIntoView({behavior:'smooth',block:'start'}),50)}if(event.target.matches('[data-start-boss]'))startBossFight();if(event.target.matches('[data-boss-inc]'))updateBossProgress(event.target.dataset.bossInc,1);if(event.target.matches('[data-boss-dec]'))updateBossProgress(event.target.dataset.bossDec,-1)})}
function bossObjectives(){const exam=state.hunterExams[0];if(!exam)return [];return bossMetrics.filter(metric=>Number(exam[metric.key]||0)>0).map(metric=>({key:metric.key,label:metric.label,target:Math.ceil(Number(exam[metric.key])*1.25),unit:metric.unit,base:Number(exam[metric.key])}))}
function bossName(){return 'Ferrugem Rank '+rankKey(getRank(Number(state.rusty.maxRankXp||state.hunterRankXp||0)).name)}
function bossProgress(){const objectives=bossObjectives(),progress=state.bossFight.progress||{};if(!objectives.length)return{done:0,total:1,percent:0};const done=objectives.reduce((sum,item)=>sum+Math.min(item.target,Number(progress[item.key]||0)),0),total=objectives.reduce((sum,item)=>sum+item.target,0);return{done,total,percent:Math.min(100,Math.round(done/total*100))}}
function renderBossFight(){const panel=document.getElementById('bossFightPanel');if(!panel)return;if(state.bossFight.status==='won'){panel.innerHTML=`<article class='boss-end victory'><p class='eyebrow'>Boss Fight concluido</p><h2>VITORIA</h2><div class='boss-rewards'><span>XP restaurado: +100</span><span>Status removido</span><span>Rank restaurado</span></div><button class='primary-button' type='button' data-open-boss>Ver Boss Fights</button></article>`;return}if(!isRusty()){panel.innerHTML=`<article class='boss-empty'><p class='eyebrow'>Boss Fights</p><h2>Nenhum Boss ativo</h2><p>O Boss Fight e desbloqueado quando o status Enferrujado estiver ativo.</p></article>`;return}const objectives=bossObjectives();if(!objectives.length){panel.innerHTML=`<article class='boss-empty'><p class='eyebrow'>Boss Fights</p><h2>Sem base Hunter</h2><p>Conclua um Exame Hunter para gerar automaticamente o Boss Fight.</p></article>`;return}if(state.bossFight.active&&Date.now()>=state.bossFight.endsAt)failBossFight(false);const active=state.bossFight.active,remaining=active?Math.max(0,Math.ceil((state.bossFight.endsAt-Date.now())/1000)):bossTimeCapSeconds,progress=state.bossFight.progress||{},summary=bossProgress();panel.innerHTML=`<article class='boss-arena'><div class='boss-topline'><p class='eyebrow'>Boss Fight</p><span class='pill'>Time Cap: ${Math.floor(bossTimeCapSeconds/60)} min</span></div><h2>${bossName()}</h2><div id='bossTimer' class='boss-timer'>${formatTimer(remaining)}</div><div class='boss-progress'><div class='boss-progress-fill' style='width:${summary.percent}%'></div></div><div class='boss-progress-text'><span>${summary.done} / ${summary.total}</span><strong>${summary.percent}%</strong></div><p class='boss-rule'>Objetivos gerados com aproximadamente 125% do ultimo Exame Hunter. Divida em quantas series quiser. O cronometro nao pode ser pausado.</p><div class='boss-objectives'>${objectives.map(item=>bossObjective(item,progress,active)).join('')}</div><div class='form-actions'>${active?`<span class='pill boss-running'>Cronometro ativo</span>`:`<button class='primary-button' type='button' data-start-boss>${state.bossFight.status==='failed'?'Tentar novamente':'Iniciar Boss Fight'}</button>`}<span class='pill'>${active?'Em combate':'Aguardando inicio'}</span></div>${state.bossFight.status==='failed'?`<article class='boss-end defeat compact'><h3>DERROTA</h3><p>O tempo acabou. O status Enferrujado permanece. Tente novamente quando quiser.</p></article>`:''}</article>`;if(active)startBossTimer()}
function bossObjective(item,progress,active){const value=Math.min(item.target,Number(progress[item.key]||0)),done=value>=item.target;return `<article class='boss-objective ${done?'done':''}'><div><strong>${item.label}</strong><small>Base ${item.base}${item.unit} -> Boss ${item.target}${item.unit}</small></div><div class='boss-counter'><button type='button' data-boss-dec='${item.key}' ${!active||value<=0?'disabled':''}>-1</button><span>${value} / ${item.target}</span><button type='button' data-boss-inc='${item.key}' ${!active||done?'disabled':''}>+1</button></div></article>`}
function startBossFight(){if(!isRusty())return;const progress={};bossObjectives().forEach(item=>progress[item.key]=0);state.bossFight={active:true,startedAt:Date.now(),endsAt:Date.now()+bossTimeCapSeconds*1000,progress,status:'running'};saveState();renderBossFight()}
function startBossTimer(){if(activeBossTimer)clearInterval(activeBossTimer);activeBossTimer=setInterval(()=>{if(!state.bossFight.active){clearInterval(activeBossTimer);return}const remaining=Math.max(0,Math.ceil((state.bossFight.endsAt-Date.now())/1000)),timer=document.getElementById('bossTimer');if(timer)timer.textContent=formatTimer(remaining);if(remaining<=0)failBossFight(true)},1000)}
function updateBossProgress(key,delta){if(!state.bossFight.active)return;const objectives=bossObjectives(),objective=objectives.find(item=>item.key===key);if(!objective)return;const progress={...(state.bossFight.progress||{})},current=Number(progress[key]||0);progress[key]=Math.max(0,Math.min(objective.target,current+delta));state.bossFight.progress=progress;if(objectives.length&&objectives.every(item=>Number(progress[item.key]||0)>=item.target)&&Date.now()<=state.bossFight.endsAt){completeBossFight();return}saveState();renderBossFight()}
function completeBossFight(){if(activeBossTimer)clearInterval(activeBossTimer);state.rusty={...state.rusty,active:false,clearedForTrainingDate:state.rusty.lastTrainingDate||''};state.totalXp+=100;state.bossFight={...state.bossFight,active:false,status:'won',endedAt:Date.now()};saveState();renderAll();switchTab('boss')}
function failBossFight(shouldRender){if(activeBossTimer)clearInterval(activeBossTimer);state.bossFight={...state.bossFight,active:false,status:'failed',endedAt:Date.now()};saveState();if(shouldRender){renderAll();switchTab('boss')}}
renderHistory=function(){const hunterCards=(state.hunterExams||[]).map(renderHunterExamCard),recordCards=(state.records||[]).map(r=>`<article class='history-card'><div class='section-title'><h3>${formatDate(r.date)}</h3><span class='pill'>+${calculateRecordXp(r)} XP</span></div><div class='history-meta'><span>${r.weight||'-'} kg</span><span>Flexoes ${r.maxPushups||'-'}</span><span>Barras ${r.maxPullups||'-'}</span><span>Prancha ${r.maxPlank||'-'}s</span><span>Futebol ${r.footballRating||'-'}/5</span></div><p>${trainingSummary(r)}</p>${painSummary(r)?'<p><strong>Alertas:</strong> '+painSummary(r)+'</p>':''}${r.notes?'<p>'+escapeHtml(r.notes)+'</p>':''}</article>`);historyCount.textContent=hunterCards.length+recordCards.length+' registros';renderEvolution();historyList.innerHTML=hunterCards.length||recordCards.length?hunterCards.concat(recordCards).join(''):`<article class='panel'><p>Nenhum registro ainda. Salve seu primeiro check-in semanal ou conclua um Exame Hunter.</p></article>`};
})();
